apiVersion: v1
kind: Namespace
metadata:
  name: uber-clone
  labels:
    app: uber-clone
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uber-clone-config
  namespace: uber-clone
data:
  environment: "development"
  http-addr: ":8080"
  app-url: "http://localhost:3000"
  stripe-success-url: "http://localhost:3000?payment=success"
  stripe-cancel-url: "http://localhost:3000?payment=cancel"
  exporter-endpoint: "http://jaeger-collector:4318"