apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: uber-clone
type: Opaque
stringData:
  uri: "<your_mongodb_uri>"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
  namespace: uber-clone
type: Opaque
stringData:
  osrm: "http://router.project-osrm.org/route/v1/driving"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe
  namespace: uber-clone
type: Opaque
stringData:
  stripe-secret-key: "<sk_test_your_key_here>"
  stripe-webhook-key: "<your_stripe_webook_key>"
  stripe-publishable-key: "<pk_test_your_key_here>"