apiVersion: v1
kind: Namespace
metadata:
  name: heygo
  labels:
    app: heygo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heygo-config
  namespace: heygo
data:
  environment: "development"
  http-addr: ":8080"
  app-url: "http://localhost:3000"
  allowed-origins: "http://localhost:3000"
  casperid-jwks-url: "https://casperid.com/.well-known/jwks.json"
  casperid-issuer: "casperid.com"
  casperid-base-url: "https://casperid.com"
  casperid-token-url: "https://apis.casperid.com/api/oauth/token"
  casperid-driver-redirect-uri: "com.heygo.driver://oauth/callback"
  monnify-base-url: "https://sandbox.monnify.com"
  monnify-redirect-url: "http://localhost:3000?payment=pending"
  exporter-endpoint: "http://jaeger-collector:4318"
  gcp-project-id: "heygo-ng"
