apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: uber-clone
type: Opaque
stringData:
  url: "postgres://<user>:<password>@<host>:5432/<database>?sslmode=require"
  internal-service-token: "<generate-a-long-random-token>"
---
apiVersion: v1
kind: Secret
metadata:
  name: casperid
  namespace: uber-clone
type: Opaque
stringData:
  app-id: "<your_casperid_business_app_id>"
  api-secret: "<your_casperid_business_api_secret>"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
  namespace: uber-clone
type: Opaque
stringData:
  osrm: "http://router.project-osrm.org/route/v1/driving"
---
apiVersion: v1
kind: Secret
metadata:
  name: moniepoint
  namespace: uber-clone
type: Opaque
stringData:
  api-key: "<your_monnify_api_key>"
  secret-key: "<your_monnify_secret_key>"
  contract-code: "<your_monnify_contract_code>"
